project:
  type: website
  output-dir: docs

website:
  title: "Ivan D. Rueda"
  navbar:
    background: "#101820" 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/ivandrueda
        aria-label: GitHub
format:
  html:
    theme: flatly
    css: styles.css
    toc: true