project:
  type: website
  output-dir: docs

website:
  title: "Ivan D. Rueda"
  site-url: "http://ivandrueda.github.io"
  navbar:
    background: "#101820" 
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ivan-rueda-b720685a/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/ivandrueda
        aria-label: GitHub

format:
  html:
    theme: flatly
    css: styles.css
    toc: true