project:
  type: website
  output-dir: docs

website:
  title: "Ivan D. Rueda"
  site-url: "http://ivandrueda.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: portfolio.qmd
        text: Portfolio
      # - href: blog.qmd
      #   text: Blog

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ivan-rueda-b720685a/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/ivandrueda
        aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - styles.scss
    # css: styles.css
    toc: true